Auto Deflate-Raw Support
Fully added support for determining the compression format used by the file, which will now work for all of the formats: `gzip`, `deflate`, and `deflate-raw`!

This might not sound new, because the library has supported explicitly opening all three formats for the last month or so. Now it will be able to automatically open files that are compressed with `deflate-raw`, you don't have to explicitly mention if it is `deflate-raw` or not, to open it successfully.

Been working on adding support for the this the last 4 days or so, and I hit multiple roadblocks along the way.

So firstly, I realized that there isn't as easy of a way to detect a `deflate-raw`-encoded data using the same header technique that I use for the other two formats, because the raw data simply doesn't have a header that you can check against. There might be a way to write some fancy logic to detect it, but I realized that it might be better in terms of being more explicit/reliable to simply just try parsing the data itself, and seeing what happens. While reading across multiple articles online about other people trying to do the same thing, many of the main responses said that just trying to parse the data will be the most efficient, because it will fail fast once something in the data isn't correct.

After thinking about that for a bit, coming back the last few days to try this was the next step. Then I started running into errors while having everything set up. It was seemingly random, in the fact that wrapping the new code in try-catch blocks wouldn't catch where any of the errors were.

While debugging it for about a full day or two, my head was starting to spin and I was getting a bit frustrated. I tried breaking the code out into it's own file to try and debug where the error was, and it started working magically. Then I realized it must be something with the Node `deflate-raw` polyfill I added recently, so I added that in to see if that would break the working code (it didn't). I was really happy that it was working, but I was even moreso concerned that the orignal code wasn't working, having learned everything else that *was* indeed working. Then I had a last attempt idea, maybe it was the `pipeThroughCompressionStream()` function? That wouldn't make any sense. But, I'll try adding that to my standalone code, see what happens.

```ts
const data = Uint8Array.from({ length: 25 },() => 25);
console.log(data);

const compressed = await compress(data,"deflate-raw");
console.log(compressed);

const unzipped = await unzip(compressed);
console.log(unzipped);

async function unzip(data: Uint8Array): Promise<Uint8Array> {
  try {
    return await decompress(data,"gzip");
  } catch {
    try {
      return await decompress(data,"deflate");
    } catch {
      try {
        return await decompress(data,"deflate-raw");
      } catch {
        throw new Error("Could not unzip the buffer data");
      }
    }
  }
}

async function compress(data: Uint8Array, format: CompressionFormat): Promise<Uint8Array> {
  try {
    const compressionStream = new CompressionStream(format);
    return pipeThroughCompressionStream(data,compressionStream);
  } catch (error){
    if (format !== "deflate-raw") throw error;
    // @ts-expect-error
    const { deflateRawSync } = await import("node:zlib");
    return new Uint8Array(deflateRawSync(data));
  }
}

async function decompress(data: Uint8Array, format: CompressionFormat): Promise<Uint8Array> {
  try {
    const decompressionStream = new DecompressionStream(format);
    return pipeThroughCompressionStream(data,decompressionStream);
  } catch (error){
    if (format !== "deflate-raw") throw error;
    // @ts-expect-error
    const { inflateRawSync } = await import("node:zlib");
    return new Uint8Array(inflateRawSync(data));
  }
}

async function pipeThroughCompressionStream(data: Uint8Array, { readable, writable }: CompressionStream | DecompressionStream): Promise<Uint8Array> {
  const writer = writable.getWriter();

  writer.write(data);
  writer.close();

  const chunks: Uint8Array[] = [];
  let byteLength = 0;

  const generator = (Symbol.asyncIterator in readable) ? readable : readableStreamToAsyncGenerator(readable as ReadableStream<Uint8Array>);

  for await (const chunk of generator){
    chunks.push(chunk);
    byteLength += chunk.byteLength;
  }

  const result = new Uint8Array(byteLength);
  let byteOffset = 0;

  for (const chunk of chunks){
    result.set(chunk,byteOffset);
    byteOffset += chunk.byteLength;
  }

  return result;
}

async function* readableStreamToAsyncGenerator<T>(readable: ReadableStream<T>): AsyncGenerator<T,void,void> {
  const reader = readable.getReader();
  try {
    while (true){
      const { done, value } = await reader.read();
      if (done) return;
      yield value;
    }
  } finally {
    reader.releaseLock();
  }
}
```

Bingo! The same error started happening. So for some reason, at least with Chrome/V8 (Node)'s Zlib implementations, you can't decompress a `deflate-raw` stream using my `pipeThroughCompressionStream()` chunker function. That was unexpected! My demo had worked fine just before this, when I had originally set it up with my old `pipeThroughCompressionStream()` implementation, just because I was too lazy to add all of the fancy logic for the chunker function version. Here's that one:

```ts
async function pipeThroughCompressionStream(data: Uint8Array, stream: CompressionStream | DecompressionStream): Promise<Uint8Array> {
  const { body } = new Response(data);
  const readable = body!.pipeThrough(stream);
  const buffer = await new Response(readable).arrayBuffer();
  return new Uint8Array(buffer);
}
```

So yeah, that was an interesting find. And for reference, this is the error code that you get from running this in the console:

```log
Error: incorrect header check
    at __node_internal_genericNodeError (node:internal/errors:865:15)
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

I hopefully would like to delve into this a bit more, and figure out why this is an issue. Maybe I'm missing something inside of the `pipeThroughCompressionStream()` function, and that's all that needs help, it might not be Zlib's issue afterall (or rather, my use of it).

This chunker version of the function has proven from the test we've done here has shown (https://github.com/Offroaders123/Dovetail/issues/1), so ideally I'd like to use that version to decompress the data, but this one will work every time, so I'm going with this old version since it is reliably successful, albeit a little slower (not really, just in the grand scheme of things).

(https://github.com/Offroaders123/NBTify/issues/11)

I'm also debating as of writing this, that it makes sense to provide both ways of doing this auto-detection, since it is faster and less recursive in terms of format parsing if you check the headers of the files before trying to parse them with `x` format (you already know before trying to open it, so you can just open it with the right one to start with), and it also could just use this old non-chunked version for `deflate-raw` specifically, since it works great for the other two formats. I'm deciding not to worry about that with this initial find/addition/fix/discovery though, as having it working for all features is more important to me than having it work the absolute greatest too. I don't want to overcomplicate things just because it might be faster, I want to demo things out more to instead see if I can fix that chunking issue, and add `deflate-raw` support to it, so there would only have to be one `pipeThroughCompressionStream()` function, not two. And I also like the simplification that this headerless auto-decompression handling provides, so I'm going with that one only for the time being, because it is easier for me to understand at the moment. Once again, eventually when I can find benefits to having both, if it makes the others faster, than I will add both because it could simplify the reading process, and have less format checking to do, for the parts that are explicit in how they are formatted (the compression headers).

I may also go this way with the Bedrock Level header, but that mostly depends on if I go all-in on the auto-reading try-catch behavior for compression too, since they are similar in terms of the header-checking behavior.

So here's a mental summary (for you and myself):

I'm going with absolute-support first, leaving performance to be picked up later. I want to ensure that everything is working up to par, then worry about possible performance gains after that. Ideally, I eventually want to have both. But in the meantime, I want to rely on features that fully work, without any inconsistencies or things that could cause spaghettic code (typo, was neat. keeping that; spaghettic - to be spaghetti-like; use: that code is very spaghettic.).